#!/bin/bash

gnome-screenshot -a -c

image=$(xclip -out -sel clip -t image/png | base64 --wrap=0)

code="<img src="\""data:image/png;base64, $image"\"" alt="\""copied img"\"">"

printf "%s" "$code" | xclip -in -selection clipboard


